export const PRODUCT_CATEGORIES = [

  "AI Agents",
  "Video Generators",
  "Chat & Assistants",
  "Voice Cloning & Synthesis",

  // "3D Models & Assets",
  // "Virtual Agents",
  // "Detection Tools",
  // "Utility Apps",
  // "Featured Picks",
  // "Creative Tools",
  // "Digital Art & Design",
  // "Code Assistance",
  // "Assistive Technology",
    // "Audio & Sound Editing",
  // "Automation & Workflows",
  // "Avatar & Character Creators",
  // "Business Solutions",
  // "Chatbot Builders",
  // "Customer Support",
  // "Data & Insights",
  // "Dating & Relationships",
  // "Developer Resources",
  // "E-Commerce & Shops",
  // "Email Tools & Automation",
  // "Education & Learning",
  // "Software Extensions",
  // "Face Swap & Deepfake",
  // "Fashion & Style",
  // "Files & Spreadsheet Tools",
  // "Finance & Budgeting",
  // "Future Tech",
  // "Gaming & Interactive Tools",
  // "GitHub Projects",
  // "Healthcare & Medicine",
  // "HR & Hiring Tools",
  // "Image Editing & Design",
  "Image Generators",
  // "Latest Innovations",
  // "Legal & Compliance Tools",
  // "Life Assistance",
  // "Large Language Models (LLM)",
  // "Logo & Branding",
  // "Marketing & Advertising",
  // "Memory & Productivity Boosters",
  // "Music & Sound Generation",
  // "No-Code & Low-Code Platforms",
  // "Presentation & Slide Tools",
  // "Productivity & Organization",
  // "Prompts & Writing Aids",
  // "Real Estate & Architecture",
  // "Research & Science",
  // "Robots & Devices",
  // "Sales & Conversion Tools",
  // "Search Engines",
  // "Social Media & Networking",
  // "Storytelling & Writing",
  // "Text Summarization",
  // "Top SuperTools",
  // "Text & Content Generators",
  // "Text-to-Speech",
  // "Video Creation",
  // "Unique Projects",
  // "Transcription & Audio to Text",
  // "Language Translation",
  // "Travel & Trip Planning",
  // "Video Editing",
  // "Video Generators",

  // "Web Design & Development",
  // "Writing & SEO Optimization",
];